version: 2

models:
    - name: posts_answer_dim
      description:
      columns:
          -name: id
           description: PK
           tests:
               - unique
               - not_null
          
          -name: accepted_answer_id
           description: 
           tests:
               - unique
               

          -name: post_type_id
           description: 
           tests:
               - not_null
          
          -name: parent_id
           description: 
           tests:
               - unique
               
          
          -name: answer_count
           description: 
           tests:
               - not_null
          
          -name: comment_count
           description: 
           tests:
               - not_null
          
          -name: favourite_count
           description: 
           tests:
                
          -name: score
           description: 
           tests:
         
          -name: tags
           description: 
           tests:
               - not_null

    - name: posts_content_dim
      description:
      columns:
           -name: id
           description: PK
           tests:
               - unique
               - not_null

          -name: post_type_id
           description:
           tests:
               - not_null

          -name: title
           description:
           tests:
               - not_null

          -name: body
           description:
           tests:
               - not_null

          -name: score
           description:
           tests:

          -name: tags
           description:
           tests:
               - not_null

    - name: posts_editor_dim
      description:
      columns:
          -name: id
           description: PK
           tests:
               - unique
               - not_null

          -name: last_editor_user_id
           description:
           tests:
               - unique
               - not_null

          -name: last_editor_display_name
           description:
           tests:
               - not_null

              
    - name: posts_fact
      description:
      columns:
          -name: id
           description: PK
           tests:
               - unique
               - not_null

          -name: accepted_answer_id
           description: FK
           tests:

          -name: last_editor_user_id
           description: FK
           tests:

          -name: owner_user_id
           description: FK
           tests:
               - unique
               - not_null

          -name: parent_id
           description: fk
           tests:

          -name: post_type_id
           description: fk
           tests:
               - not_null

          -name: tags
           description: 
           tests:

    - name: posts_owner_dim
      description: 
      columns:
          -name: id
           description: PK
           tests:
               - unique
               - not_null

          -name: owner_user_id
           description: fk
           tests:
               - unique
               - not_null

          -name: owner_display_name
           description:
           tests:
               - not_null

          -name: last_activity_date
           description:
           tests:
               - not_null

          -name: comment_count
           description:
           tests:

          -name: score
           description:
           tests:
    
    - name: posts_time_dim
      description:
      columns:
          -name: id
           description: PK
           tests:
               - unique
               - not_null

          -name: community_owned_date
           description:
           tests:

          -name: creation_date
           description:
           tests:
               - not_null

          -name: last_activity_date
           description:
           tests:
               - not_null

          -name: last_edit_date
           description:
           tests:
               - not_null